"""empty message

Revision ID: 0b60a01b5ae9
Revises: 2b958ee641e5
Create Date: 2018-07-12 12:49:29.610000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b60a01b5ae9'
down_revision = '2b958ee641e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('shortName', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'shortName')
    # ### end Alembic commands ###
