"""empty message

Revision ID: f8be117c757c
Revises: 0b60a01b5ae9
Create Date: 2018-07-12 13:36:22.757000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8be117c757c'
down_revision = '0b60a01b5ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctors', 'addressId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(u'doctors_ibfk_3', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'addresses', ['addressId'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key(u'doctors_ibfk_3', 'doctors', 'addresses', ['addressId'], ['id'])
    op.alter_column('doctors', 'addressId',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
